apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-statefulset
  namespace: observability
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  # serviceName: example-service
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: jaegertracing/vertx-create-span:operator-e2e-tests
          ports:
            - containerPort: 8080
              protocol: TCP
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:1.17.0  # The agent version should match the operator version
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
              name: zk-compact-trft
              protocol: UDP
            - containerPort: 5778
              name: config-rest
              protocol: TCP
            - containerPort: 6831
              name: jg-compact-trft
              protocol: UDP
            - containerPort: 6832
              name: jg-binary-trft
              protocol: UDP
            - containerPort: 14271
              name: admin-http
              protocol: TCP
          args:
            - --reporter.grpc.host-port=dns:///jaeger-collector.observability:14250

---

apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: observability
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080